### ISSUE TITLE
Breaks in typescript 4.8

### ISSUE THREAD

**Issue by hpx7** [yandeu/events#1]
Works with typescript 4.7.4, breaks in 4.8.2+
```
node_modules/@yandeu/events/cjs/index.d.ts:16:170 - error TS2344: Type 'T[K]' does not satisfy the constraint 'Object | ((...args: any[]) => void)'.
  Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'Object | ((...args: any[]) => void)'.
    Type 'T[string]' is not assignable to type 'Object | ((...args: any[]) => void)'.
      Type 'T[string]' is not assignable to type 'Object'.
        Type 'T[K]' is not assignable to type 'Object'.
          Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'Object'.
            Type 'T[string]' is not assignable to type 'Object'.

16 export declare type EventListener<T extends ValidEventMap, K extends EventNames<T>> = T extends string | symbol ? (...args: any[]) => void : K extends keyof T ? Handler<T[K], void> : never;
                                                                                                                                                                            ~~~~


Found 1 error in node_modules/@yandeu/events/cjs/index.d.ts:16
```

**Comment by yandeu** [comment]
Looks like it is because of this:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#correctness-fixes-and-breaking-changes

**Comment by yandeu** [comment]
I don't know how to fix it, so I just put an `any` for now.
